name: Build Peass libraries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *"
jobs:
  build:
    strategy: 
        matrix:
          os: [ubuntu-latest, windows-latest] # no macos-latest since github actions always procudes EDTIMEOUT
          java: [ 11, 17 ]
        fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} OS ${{ matrix.os }} sample
    steps:
    - name: Set Git Property and output path
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          git config --system core.longpaths true
          echo %PATH%
          where mvn
          mvn -version
        fi
      shell: bash
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.8.5
    - name: Test Maven Version
      run: mvn -version
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: cd /home/runner/work/ && git clone -b develop https://github.com/DaGeRe/peass.git && cd peass && mvn clean install -DskipTests
    - name: Build Peass dependency, measurement and analysis
      run: ./mvnw -B install --file pom.xml
    - name: Publish Test Report ${{ matrix.java }} OS ${{ matrix.os }}
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         check_name: Test Report ${{ matrix.java }} OS ${{ matrix.os }}
    - name: Upload Unit Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results (Java ${{ matrix.java }} OS ${{ matrix.os }})
        path: |
          dependency/target/surefire-reports/*
          measurement/target/surefire-reports/*
          analysis/target/surefire-reports/*
